---
# tasks file for cvp.sync

- name: "collect CVP Facts"
  tags:
    - sync
    - check
  arista.cvp.cv_facts:
  register: CVP_FACTS

- name: "Extract shared Configlets"
  tags:
     - sync
     - check
  template:
    src: "template.shared_configlets.j2"
    dest: "./generated_vars/common_configlets/{{inventory_hostname}}.yml"
  delegate_to: localhost
  run_once: False

- name: "Load Common CVP Servers Configlet Data"
  tags:
    - sync
    - check
  include_vars:
     file: './generated_vars/common_configlets/master.yml'
     name: 'shared_master'
  delegate_to: localhost

- name: "Load CVP Instance Shared Configlet Data"
  tags:
    - sync
    - check
  include_vars:
     file: "./generated_vars/common_configlets/{{inventory_hostname}}.yml"
     name: 'shared_server'
  delegate_to: localhost

- name: "Compare shared Configlets"
  tags:
    - sync
    - check
  template:
    src: "template.compare_configlets.j2"
    dest: "./generated_vars/common_configlets/master.yml"
  delegate_to: localhost
