---
- name: Test cv_device
  hosts: cvp_servers
  connection: local
  gather_facts: no
  collections:
    - arista.cvp
  vars:
    configlet_list:
      ansible_device_test01: "alias a{{ 999 | random }} show version"
      ansible_device_test02: "alias a{{ 999 | random }} show version"
      CTL1-EXT-PRDSW-001_base-ansible: "{{ lookup('file', 'templates/CTL1-EXT-PRDSW-001_base-ansible.txt') }}"
    # Device inventory for provision activity: bind configlet
    devices_inventory:
      CTL1-EXT-PRDSW-001:
        name: CTL1-EXT-PRDSW-001
        configlets:
          - ansible_device_test01
          - CTL1-EXT-PRDSW-001_base-ansible
        parentContainerName: "provision"
        imageBundle: ""
    # Device inventory for rollback activity: unbind configlet
    devices_inventory_rollback:
      CTL1-EXT-PRDSW-001:
        name: CTL1-EXT-PRDSW-001
        configlets:
          - CTL1-EXT-PRDSW-001_base-ansible

  tasks:
      # Collect CVP Facts as init process
    - name: "Gather CVP facts from {{inventory_hostname}}"
      cv_facts:
      register: cvp_facts
      tags:
        - always

###################################################
### Provision
###################################################

    - name: 'Create configlets on CVP {{inventory_hostname}}.'
      tags:
        - provision
      cv_configlet:
        cvp_facts: "{{cvp_facts.ansible_facts}}"
        configlets: "{{configlet_list}}"
        configlet_filter: ["ansible"]
      register: cvp_configlet

    - name: "Configure devices on {{inventory_hostname}}"
      tags:
        - provision
      cv_device:
        devices: "{{devices_inventory}}"
        cvp_facts: '{{cvp_facts.ansible_facts}}'
        device_filter: ['PRDSW']
      register: cvp_device

###################################################
### Cleanup
###################################################

    - name: "Rollback configlet on devices on {{inventory_hostname}}"
      tags:
        - cleanup
      cv_device:
        devices: "{{devices_inventory_rollback}}"
        cvp_facts: '{{cvp_facts.ansible_facts}}'
        device_filter: ['PRDSW']
      register: cvp_device

###################################################
### Reset
###################################################

    - name: "Reset devices on {{inventory_hostname}}"
      tags:
        - reset
      cv_device:
        devices: "{{devices_inventory_rollback}}"
        cvp_facts: '{{cvp_facts.ansible_facts}}'
        device_filter: ['PRDSW']
        state: "absent"
      register: cvp_device

###################################################
### Show Result
###################################################

    - name: Display cv_device
      tags:
        - always
      debug:
        msg: "{{cvp_device}}"
