---
- name: Test cv_device
  hosts: cvp_servers
  connection: local
  gather_facts: no
  collections:
    - arista.cvp
  vars:
    configlet_list:
      ansible_device_test01: "alias a{{ 999 | random }} show version"
      ansible_device_test02: "alias a{{ 999 | random }} show version"
    # Device inventory for provision activity: bind configlet
    devices_inventory:
      veos01:
        name: CTL1-EXT-PRDSW-001
        configlets:
          - ansible_device_test01
          - CTL1-EXT-PRDSW-001_base-ansible
    # Device inventory for rollback activity: unbind configlet
    devices_inventory_rollback:
      veos01:
        name: CTL1-EXT-PRDSW-001
        configlets:
          - CTL1-EXT-PRDSW-001_base-ansible
          - veos01-basic-configuration

  tasks:
      # Collect CVP Facts as init process
    - name: "Gather CVP facts from {{inventory_hostname}}"
      cv_facts:
      register: cvp_facts
      tags:
        - always

###################################################
### Provision
###################################################

    - name: 'Create configlets on CVP {{inventory_hostname}}.'
      tags:
        - provision
      cv_configlet:
        cvp_facts: "{{cvp_facts.ansible_facts}}"
        configlets: "{{configlet_list}}"
        configlet_filter: ["cv_device_test"]
      register: cvp_configlet

    # Display information for device before a container's move
    - name: "Configure devices on {{inventory_hostname}}"
      tags:
        - provision
      cv_device:
        devices: "{{devices_inventory}}"
        cvp_facts: '{{cvp_facts.ansible_facts}}'
        device_filter: ['veos']
      register: cvp_device

    - name: Display cv_device
      tags:
        - provision
      debug:
        msg: "{{cvp_device}}"

###################################################
### Cleanup
###################################################

    # Display information for device before a container's move
    - name: "Rollback configlet on devices on {{inventory_hostname}}"
      tags:
        - cleanup
      cv_device:
        devices: "{{devices_inventory_rollback}}"
        cvp_facts: '{{cvp_facts}}'
        device_filter: ['veos']
      register: cvp_device

    - name: Display cv_device
      tags:
        - cleanup
      debug:
        msg: "{{cvp_device}}"
