---
- name: Test and validation for cv_facts module.
  hosts: cvp_servers
  connection: local
  gather_facts: no
  collections:
    - arista.cvp
  vars:
    - verbose: False
    - cloudvision_topology:
        configlets:
          - configletName: ansible_Configlet_test01
            data: "{{playbook_dir}}/templates/configlet1.txt"
          - configletName: ansible_Configlet_test02
            data: "{{playbook_dir}}/templates/configlet2.txt"
        devices:
          - CTL1-PRD-SLEAF-001
  tasks:
    - name: "Gather CVP facts {{inventory_hostname}}"
      cv_facts:
      register: cv_facts

    - name: "Print out facts from CVP"
      debug:
        msg: "{{cv_facts}}"
      when: verbose|bool

    - name: "Check facts have expected lists"
      assert:
        that:
          - "'configlets' in cv_facts.ansible_facts"
          - "'devices' in cv_facts.ansible_facts"
          - "'containers' in cv_facts.ansible_facts"
          - "'imageBundles' in cv_facts.ansible_facts"
          - "'tasks' in cv_facts.ansible_facts"
        fail_msg: "'ansible_facts do not have expected lists"
        success_msg: "ansible_facts have all expected list from CVP"

    - name: "Check containers facts "
      assert:
        that:
          - "{{ cv_facts.ansible_facts['containers'] | length }} >1"
        fail_msg: "Facts from CVP do not return any container. (>=2 are expected)"
        success_msg: "Facts from CVP return more than 1 container as expected"

    - name: "Check if undefined container exists"
      assert:
        that:
          - "cv_facts.ansible_facts['containers'] | selectattr(search_key,'equalto',search_val) | list | count > 0"
        fail_msg: "Undefined_container has not been found in facts"
        success_msg: "undefined_container has been found as expected"
      vars:
        search_key: key
        search_val: undefined_container

    - name: "Check configlets facts "
      assert:
        that:
          - "{{ cv_facts.ansible_facts['configlets'] | length }} >0"
        fail_msg: "Facts from CVP do not return any configlets. (>=1 are expected)"
        success_msg: "Facts from CVP return more than 1 configlets as expected"
    
    - name: "Gather running Configs for Devices"
      cv_facts:
        gather_subset: 
          config
        facts:
          devices
      register: cv_facts_config

    - name: "Check for Running Config from in Device Data"
      assert:
        that:
          - "{{item.config | length }} >0"
        fail_msg: "Running Config for {{item.hostname}}: NOT FOUND"
        success_msg: "Running Config for {{item.hostname}}: FOUND"
      with_items:
        - "{{cv_facts_config.ansible_facts['devices']}}"
      #when: item.hostname in cloudvision_topology.devices