---
  bgp:
    asn: 65080.2002
  endpoint_services:
    - name: ClientAccess
      vlan: 51
      svi: 192.168.51.1/24
      svi_mode: local
      interfaces:
        - name: Ethernet7
          description: CTL1-SRV-labtest-002-eth0
