---
  bgp:
    asn: 65080.2002
  endpoint_services:
    - name: ClientAccess
      vlan: 52
      svi: 192.168.52.1/24
      svi_mode: local
      interfaces:
        - name: Ethernet7
          description: CTL1-SRV-labtest-003-eth0
