---
  bgp:
    asn: 65080.2001
  endpoint_services:
    - name: ClientAccess
      vlan: 50
      svi: 192.168.50.1/24
      svi_mode: local
      interfaces:
        - name: Ethernet7
          description: CTL1-SRV-labtest-001-eth0
