---
  bgp:
    asn: 65081.2002
  endpoint_services:
    - name: webservice01
      vlan: 62
      svi: 192.168.62.1/24
      svi_mode: local
      interfaces:
        - name: Ethernet7
          description: EndPoint_Client_C - eth0
